---
"name": "fabric-network"
"x-type": "hlfv1"
"version": "1.0.0"
"channels":
  "generalpoechannel":
    "orderers":
    - "orderer1.cdac.com"
    - "orderer2.cdac.com"
    - "orderer3.cdac.com"
    - "orderer4.cdac.com"
    - "orderer5.cdac.com"
    "peers":
    - "peer0.cdachorg.cdac.in"
    - "peer1.cdachorg.cdac.in"
    - "peer0.demoorg.cdac.in"
    - "peer1.demoorg.cdac.in"
    - "peer0.actsorg.cdac.in"
    - "peer1.actsorg.cdac.in"
"organizations":
  "actsorg.cdac.in":
    "mspid": "actsorg-cdac-in"
    "peers":
    - "peer0.actsorg.cdac.in"
    - "peer1.actsorg.cdac.in"
    "orderers": []
    "certificateAuthorities":
    - "ca1.actsorg.cdac.in"
  "cdac.com":
    "mspid": "cdac-com"
    "peers": []
    "orderers":
    - "orderer1.cdac.com"
    - "orderer2.cdac.com"
    - "orderer3.cdac.com"
    - "orderer4.cdac.com"
    - "orderer5.cdac.com"
  "cdachorg.cdac.in":
    "mspid": "cdachorg-cdac-in"
    "peers":
    - "peer0.cdachorg.cdac.in"
    - "peer1.cdachorg.cdac.in"
    "orderers": []
    "certificateAuthorities":
    - "ca1.cdachorg.cdac.in"
  "demoorg.cdac.in":
    "mspid": "demoorg-cdac-in"
    "peers":
    - "peer0.demoorg.cdac.in"
    - "peer1.demoorg.cdac.in"
    "orderers": []
    "certificateAuthorities":
    - "ca1.demoorg.cdac.in"

"orderers":
  "orderer1.cdac.com":
    "url": "grpcs://10.109.168.201:7009"
    "grpcOptions":
      "ssl-target-name-override": "orderer1.cdac.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICjzCCAjagAwIBAgIUVvRF6/gUIzuGuPLQ2mBqJErCxBQwCgYIKoZIzj0EAwIw\nZDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMREwDwYDVQQKDAhjZGFjLmNvbTEXMBUGA1UEAwwOdGxzY2EuY2Rh\nYy5jb20wHhcNMjExMDI4MjE1MTQ4WhcNMzExMDI2MjE1MTQ4WjBkMQswCQYDVQQG\nEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gx\nETAPBgNVBAoMCGNkYWMuY29tMRcwFQYDVQQDDA50bHNjYS5jZGFjLmNvbTBZMBMG\nByqGSM49AgEGCCqGSM49AwEHA0IABENPq1bPvt3sedKhHyYyMvuOcn62V7HZd/5i\nNGSAL8U0DLBMNJPvOLke54nRMaqmh9b1z6KAfDeTM9l10IvvWbajgcUwgcIwHQYD\nVR0OBBYEFHWC4rsXpXcO5MckKjvQd17ltgl3MB8GA1UdIwQYMBaAFHWC4rsXpXcO\n5MckKjvQd17ltgl3MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0G\nA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBABgNVHREEOTA3hwQKbajJgg50\nbHNjYS5jZGFjLmNvbYIOdGxzY2EtY2RhYy1jb22CCWxvY2FsaG9zdIcEfwAAATAK\nBggqhkjOPQQDAgNHADBEAiBiuSfSlcs1USemiZ9zCDTNE908KjoDxi49m7lhyR/1\npAIgIYwiwaXAnm1kkypNm7JIlvEzm9eYvNgKSTAWjDU7rLs=\n-----END CERTIFICATE-----"
  "orderer2.cdac.com":
    "url": "grpcs://10.109.168.201:7010"
    "grpcOptions":
      "ssl-target-name-override": "orderer2.cdac.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICjzCCAjagAwIBAgIUVvRF6/gUIzuGuPLQ2mBqJErCxBQwCgYIKoZIzj0EAwIw\nZDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMREwDwYDVQQKDAhjZGFjLmNvbTEXMBUGA1UEAwwOdGxzY2EuY2Rh\nYy5jb20wHhcNMjExMDI4MjE1MTQ4WhcNMzExMDI2MjE1MTQ4WjBkMQswCQYDVQQG\nEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gx\nETAPBgNVBAoMCGNkYWMuY29tMRcwFQYDVQQDDA50bHNjYS5jZGFjLmNvbTBZMBMG\nByqGSM49AgEGCCqGSM49AwEHA0IABENPq1bPvt3sedKhHyYyMvuOcn62V7HZd/5i\nNGSAL8U0DLBMNJPvOLke54nRMaqmh9b1z6KAfDeTM9l10IvvWbajgcUwgcIwHQYD\nVR0OBBYEFHWC4rsXpXcO5MckKjvQd17ltgl3MB8GA1UdIwQYMBaAFHWC4rsXpXcO\n5MckKjvQd17ltgl3MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0G\nA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBABgNVHREEOTA3hwQKbajJgg50\nbHNjYS5jZGFjLmNvbYIOdGxzY2EtY2RhYy1jb22CCWxvY2FsaG9zdIcEfwAAATAK\nBggqhkjOPQQDAgNHADBEAiBiuSfSlcs1USemiZ9zCDTNE908KjoDxi49m7lhyR/1\npAIgIYwiwaXAnm1kkypNm7JIlvEzm9eYvNgKSTAWjDU7rLs=\n-----END CERTIFICATE-----"
  "orderer3.cdac.com":
    "url": "grpcs://10.109.168.201:7011"
    "grpcOptions":
      "ssl-target-name-override": "orderer3.cdac.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICjzCCAjagAwIBAgIUVvRF6/gUIzuGuPLQ2mBqJErCxBQwCgYIKoZIzj0EAwIw\nZDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMREwDwYDVQQKDAhjZGFjLmNvbTEXMBUGA1UEAwwOdGxzY2EuY2Rh\nYy5jb20wHhcNMjExMDI4MjE1MTQ4WhcNMzExMDI2MjE1MTQ4WjBkMQswCQYDVQQG\nEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gx\nETAPBgNVBAoMCGNkYWMuY29tMRcwFQYDVQQDDA50bHNjYS5jZGFjLmNvbTBZMBMG\nByqGSM49AgEGCCqGSM49AwEHA0IABENPq1bPvt3sedKhHyYyMvuOcn62V7HZd/5i\nNGSAL8U0DLBMNJPvOLke54nRMaqmh9b1z6KAfDeTM9l10IvvWbajgcUwgcIwHQYD\nVR0OBBYEFHWC4rsXpXcO5MckKjvQd17ltgl3MB8GA1UdIwQYMBaAFHWC4rsXpXcO\n5MckKjvQd17ltgl3MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0G\nA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBABgNVHREEOTA3hwQKbajJgg50\nbHNjYS5jZGFjLmNvbYIOdGxzY2EtY2RhYy1jb22CCWxvY2FsaG9zdIcEfwAAATAK\nBggqhkjOPQQDAgNHADBEAiBiuSfSlcs1USemiZ9zCDTNE908KjoDxi49m7lhyR/1\npAIgIYwiwaXAnm1kkypNm7JIlvEzm9eYvNgKSTAWjDU7rLs=\n-----END CERTIFICATE-----"
  "orderer4.cdac.com":
    "url": "grpcs://10.109.168.201:7012"
    "grpcOptions":
      "ssl-target-name-override": "orderer4.cdac.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICjzCCAjagAwIBAgIUVvRF6/gUIzuGuPLQ2mBqJErCxBQwCgYIKoZIzj0EAwIw\nZDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMREwDwYDVQQKDAhjZGFjLmNvbTEXMBUGA1UEAwwOdGxzY2EuY2Rh\nYy5jb20wHhcNMjExMDI4MjE1MTQ4WhcNMzExMDI2MjE1MTQ4WjBkMQswCQYDVQQG\nEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gx\nETAPBgNVBAoMCGNkYWMuY29tMRcwFQYDVQQDDA50bHNjYS5jZGFjLmNvbTBZMBMG\nByqGSM49AgEGCCqGSM49AwEHA0IABENPq1bPvt3sedKhHyYyMvuOcn62V7HZd/5i\nNGSAL8U0DLBMNJPvOLke54nRMaqmh9b1z6KAfDeTM9l10IvvWbajgcUwgcIwHQYD\nVR0OBBYEFHWC4rsXpXcO5MckKjvQd17ltgl3MB8GA1UdIwQYMBaAFHWC4rsXpXcO\n5MckKjvQd17ltgl3MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0G\nA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBABgNVHREEOTA3hwQKbajJgg50\nbHNjYS5jZGFjLmNvbYIOdGxzY2EtY2RhYy1jb22CCWxvY2FsaG9zdIcEfwAAATAK\nBggqhkjOPQQDAgNHADBEAiBiuSfSlcs1USemiZ9zCDTNE908KjoDxi49m7lhyR/1\npAIgIYwiwaXAnm1kkypNm7JIlvEzm9eYvNgKSTAWjDU7rLs=\n-----END CERTIFICATE-----"
  "orderer5.cdac.com":
    "url": "grpcs://10.109.168.201:7013"
    "grpcOptions":
      "ssl-target-name-override": "orderer5.cdac.com"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICjzCCAjagAwIBAgIUVvRF6/gUIzuGuPLQ2mBqJErCxBQwCgYIKoZIzj0EAwIw\nZDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMREwDwYDVQQKDAhjZGFjLmNvbTEXMBUGA1UEAwwOdGxzY2EuY2Rh\nYy5jb20wHhcNMjExMDI4MjE1MTQ4WhcNMzExMDI2MjE1MTQ4WjBkMQswCQYDVQQG\nEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVpZ2gx\nETAPBgNVBAoMCGNkYWMuY29tMRcwFQYDVQQDDA50bHNjYS5jZGFjLmNvbTBZMBMG\nByqGSM49AgEGCCqGSM49AwEHA0IABENPq1bPvt3sedKhHyYyMvuOcn62V7HZd/5i\nNGSAL8U0DLBMNJPvOLke54nRMaqmh9b1z6KAfDeTM9l10IvvWbajgcUwgcIwHQYD\nVR0OBBYEFHWC4rsXpXcO5MckKjvQd17ltgl3MB8GA1UdIwQYMBaAFHWC4rsXpXcO\n5MckKjvQd17ltgl3MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0G\nA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBABgNVHREEOTA3hwQKbajJgg50\nbHNjYS5jZGFjLmNvbYIOdGxzY2EtY2RhYy1jb22CCWxvY2FsaG9zdIcEfwAAATAK\nBggqhkjOPQQDAgNHADBEAiBiuSfSlcs1USemiZ9zCDTNE908KjoDxi49m7lhyR/1\npAIgIYwiwaXAnm1kkypNm7JIlvEzm9eYvNgKSTAWjDU7rLs=\n-----END CERTIFICATE-----"

"peers":
  "peer0.cdachorg.cdac.in":
    "url": "grpcs://10.109.168.201:7003"
    "grpcOptions":
      "ssl-target-name-override": "peer0.cdachorg.cdac.in"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICxDCCAmqgAwIBAgIUC3iOwpu/dVkENFUtX4SQEvVsx30wCgYIKoZIzj0EAwIw\ndTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRkwFwYDVQQKDBBjZGFjaG9yZy5jZGFjLmluMSAwHgYDVQQDDBd0\nbHNjYTEuY2RhY2hvcmcuY2RhYy5pbjAeFw0yMTEwMjgyMTUyNDhaFw0zMTEwMjYy\nMTUyNDhaMHUxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQ\nMA4GA1UEBwwHUmFsZWlnaDEZMBcGA1UECgwQY2RhY2hvcmcuY2RhYy5pbjEgMB4G\nA1UEAwwXdGxzY2ExLmNkYWNob3JnLmNkYWMuaW4wWTATBgcqhkjOPQIBBggqhkjO\nPQMBBwNCAAQFpVM3ewJ/97K/xwRsjxrPdY83k9jHV70LYAYbfvebnzpZqsMxk6V6\n1ao5F2avdeXzaH5RkXMlQ/55b2FuC2PIo4HXMIHUMB0GA1UdDgQWBBQkQepylqSS\nma8HxnNmOmwAU/cgtDAfBgNVHSMEGDAWgBQkQepylqSSma8HxnNmOmwAU/cgtDAP\nBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEF\nBQcDAQYIKwYBBQUHAwIwUgYDVR0RBEswSYcECm2oyYIXdGxzY2ExLmNkYWNob3Jn\nLmNkYWMuaW6CF3Rsc2NhMS1jZGFjaG9yZy1jZGFjLWlugglsb2NhbGhvc3SHBH8A\nAAEwCgYIKoZIzj0EAwIDSAAwRQIhAJfbGO8aYP1/jFIyFOUl+l6W0F5VPO/zHL11\nTFgFf/QXAiBfKY/P2p9UWnm5F9IQ2bLadwW2Lekm4qeOjvPBG6PK1w==\n-----END CERTIFICATE-----"
  "peer1.cdachorg.cdac.in":
    "url": "grpcs://10.109.168.201:7004"
    "grpcOptions":
      "ssl-target-name-override": "peer1.cdachorg.cdac.in"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICxDCCAmqgAwIBAgIUC3iOwpu/dVkENFUtX4SQEvVsx30wCgYIKoZIzj0EAwIw\ndTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRkwFwYDVQQKDBBjZGFjaG9yZy5jZGFjLmluMSAwHgYDVQQDDBd0\nbHNjYTEuY2RhY2hvcmcuY2RhYy5pbjAeFw0yMTEwMjgyMTUyNDhaFw0zMTEwMjYy\nMTUyNDhaMHUxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQ\nMA4GA1UEBwwHUmFsZWlnaDEZMBcGA1UECgwQY2RhY2hvcmcuY2RhYy5pbjEgMB4G\nA1UEAwwXdGxzY2ExLmNkYWNob3JnLmNkYWMuaW4wWTATBgcqhkjOPQIBBggqhkjO\nPQMBBwNCAAQFpVM3ewJ/97K/xwRsjxrPdY83k9jHV70LYAYbfvebnzpZqsMxk6V6\n1ao5F2avdeXzaH5RkXMlQ/55b2FuC2PIo4HXMIHUMB0GA1UdDgQWBBQkQepylqSS\nma8HxnNmOmwAU/cgtDAfBgNVHSMEGDAWgBQkQepylqSSma8HxnNmOmwAU/cgtDAP\nBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEF\nBQcDAQYIKwYBBQUHAwIwUgYDVR0RBEswSYcECm2oyYIXdGxzY2ExLmNkYWNob3Jn\nLmNkYWMuaW6CF3Rsc2NhMS1jZGFjaG9yZy1jZGFjLWlugglsb2NhbGhvc3SHBH8A\nAAEwCgYIKoZIzj0EAwIDSAAwRQIhAJfbGO8aYP1/jFIyFOUl+l6W0F5VPO/zHL11\nTFgFf/QXAiBfKY/P2p9UWnm5F9IQ2bLadwW2Lekm4qeOjvPBG6PK1w==\n-----END CERTIFICATE-----"
  "peer0.demoorg.cdac.in":
    "url": "grpcs://10.109.168.201:7005"
    "grpcOptions":
      "ssl-target-name-override": "peer0.demoorg.cdac.in"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICvjCCAmSgAwIBAgIUU6ZBXGmKHzI3OjIwvh7eRvyjpbgwCgYIKoZIzj0EAwIw\nczELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRgwFgYDVQQKDA9kZW1vb3JnLmNkYWMuaW4xHzAdBgNVBAMMFnRs\nc2NhMS5kZW1vb3JnLmNkYWMuaW4wHhcNMjExMDI4MjE1MzIzWhcNMzExMDI2MjE1\nMzIzWjBzMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAO\nBgNVBAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2RlbW9vcmcuY2RhYy5pbjEfMB0GA1UE\nAwwWdGxzY2ExLmRlbW9vcmcuY2RhYy5pbjBZMBMGByqGSM49AgEGCCqGSM49AwEH\nA0IABBlQ5LLVHYM/4EX+71oatHoBanOyCzwBcYRoANIV+f6CdAe42jkejfJCiFfy\n1KZJzDwdm6ZWFh3XSmheJiqak0qjgdUwgdIwHQYDVR0OBBYEFOwXrk9/qWk4JPcW\n5ALLHFFANiJnMB8GA1UdIwQYMBaAFOwXrk9/qWk4JPcW5ALLHFFANiJnMA8GA1Ud\nEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMB\nBggrBgEFBQcDAjBQBgNVHREESTBHhwQKbajJghZ0bHNjYTEuZGVtb29yZy5jZGFj\nLmlughZ0bHNjYTEtZGVtb29yZy1jZGFjLWlugglsb2NhbGhvc3SHBH8AAAEwCgYI\nKoZIzj0EAwIDSAAwRQIhAMLKJCw5O29AEYkrbWlVe0vd2Kn1fPPwk2ljEBvA4YJ7\nAiBinm6ANBUN2k2lpA/7XGpStW5d3JD75hnnBLQn5uMG0g==\n-----END CERTIFICATE-----"
  "peer1.demoorg.cdac.in":
    "url": "grpcs://10.109.168.201:7006"
    "grpcOptions":
      "ssl-target-name-override": "peer1.demoorg.cdac.in"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICvjCCAmSgAwIBAgIUU6ZBXGmKHzI3OjIwvh7eRvyjpbgwCgYIKoZIzj0EAwIw\nczELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRgwFgYDVQQKDA9kZW1vb3JnLmNkYWMuaW4xHzAdBgNVBAMMFnRs\nc2NhMS5kZW1vb3JnLmNkYWMuaW4wHhcNMjExMDI4MjE1MzIzWhcNMzExMDI2MjE1\nMzIzWjBzMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAO\nBgNVBAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2RlbW9vcmcuY2RhYy5pbjEfMB0GA1UE\nAwwWdGxzY2ExLmRlbW9vcmcuY2RhYy5pbjBZMBMGByqGSM49AgEGCCqGSM49AwEH\nA0IABBlQ5LLVHYM/4EX+71oatHoBanOyCzwBcYRoANIV+f6CdAe42jkejfJCiFfy\n1KZJzDwdm6ZWFh3XSmheJiqak0qjgdUwgdIwHQYDVR0OBBYEFOwXrk9/qWk4JPcW\n5ALLHFFANiJnMB8GA1UdIwQYMBaAFOwXrk9/qWk4JPcW5ALLHFFANiJnMA8GA1Ud\nEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMB\nBggrBgEFBQcDAjBQBgNVHREESTBHhwQKbajJghZ0bHNjYTEuZGVtb29yZy5jZGFj\nLmlughZ0bHNjYTEtZGVtb29yZy1jZGFjLWlugglsb2NhbGhvc3SHBH8AAAEwCgYI\nKoZIzj0EAwIDSAAwRQIhAMLKJCw5O29AEYkrbWlVe0vd2Kn1fPPwk2ljEBvA4YJ7\nAiBinm6ANBUN2k2lpA/7XGpStW5d3JD75hnnBLQn5uMG0g==\n-----END CERTIFICATE-----"
  "peer0.actsorg.cdac.in":
    "url": "grpcs://10.109.168.201:7007"
    "grpcOptions":
      "ssl-target-name-override": "peer0.actsorg.cdac.in"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICvTCCAmSgAwIBAgIUfKNSxaxGk65gzlc6qz4UHVbqavswCgYIKoZIzj0EAwIw\nczELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRgwFgYDVQQKDA9hY3Rzb3JnLmNkYWMuaW4xHzAdBgNVBAMMFnRs\nc2NhMS5hY3Rzb3JnLmNkYWMuaW4wHhcNMjExMDI4MjE1MTEzWhcNMzExMDI2MjE1\nMTEzWjBzMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAO\nBgNVBAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2FjdHNvcmcuY2RhYy5pbjEfMB0GA1UE\nAwwWdGxzY2ExLmFjdHNvcmcuY2RhYy5pbjBZMBMGByqGSM49AgEGCCqGSM49AwEH\nA0IABOo65SDFtGbv42c0Llv+4kHL8tNtHp2GW8jjPJpVzxdn9LvqzJJoImpbZToB\n0dzmEhCk96F/QxARYtuDlh38UlqjgdUwgdIwHQYDVR0OBBYEFKcAHgOH4GBBBj6y\noFuUF3E6+gawMB8GA1UdIwQYMBaAFKcAHgOH4GBBBj6yoFuUF3E6+gawMA8GA1Ud\nEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMB\nBggrBgEFBQcDAjBQBgNVHREESTBHhwQKbajJghZ0bHNjYTEuYWN0c29yZy5jZGFj\nLmlughZ0bHNjYTEtYWN0c29yZy1jZGFjLWlugglsb2NhbGhvc3SHBH8AAAEwCgYI\nKoZIzj0EAwIDRwAwRAIgOxh9RGz2yL1KNdSV+aOEU46pUqcEYtao4iGo28w5TzkC\nID1ZqQznQ+L5dmIbPJThBe6Ec/lzVW4CGsVtmJvnRrN/\n-----END CERTIFICATE-----"
  "peer1.actsorg.cdac.in":
    "url": "grpcs://10.109.168.201:7008"
    "grpcOptions":
      "ssl-target-name-override": "peer1.actsorg.cdac.in"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICvTCCAmSgAwIBAgIUfKNSxaxGk65gzlc6qz4UHVbqavswCgYIKoZIzj0EAwIw\nczELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRgwFgYDVQQKDA9hY3Rzb3JnLmNkYWMuaW4xHzAdBgNVBAMMFnRs\nc2NhMS5hY3Rzb3JnLmNkYWMuaW4wHhcNMjExMDI4MjE1MTEzWhcNMzExMDI2MjE1\nMTEzWjBzMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAO\nBgNVBAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2FjdHNvcmcuY2RhYy5pbjEfMB0GA1UE\nAwwWdGxzY2ExLmFjdHNvcmcuY2RhYy5pbjBZMBMGByqGSM49AgEGCCqGSM49AwEH\nA0IABOo65SDFtGbv42c0Llv+4kHL8tNtHp2GW8jjPJpVzxdn9LvqzJJoImpbZToB\n0dzmEhCk96F/QxARYtuDlh38UlqjgdUwgdIwHQYDVR0OBBYEFKcAHgOH4GBBBj6y\noFuUF3E6+gawMB8GA1UdIwQYMBaAFKcAHgOH4GBBBj6yoFuUF3E6+gawMA8GA1Ud\nEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMB\nBggrBgEFBQcDAjBQBgNVHREESTBHhwQKbajJghZ0bHNjYTEuYWN0c29yZy5jZGFj\nLmlughZ0bHNjYTEtYWN0c29yZy1jZGFjLWlugglsb2NhbGhvc3SHBH8AAAEwCgYI\nKoZIzj0EAwIDRwAwRAIgOxh9RGz2yL1KNdSV+aOEU46pUqcEYtao4iGo28w5TzkC\nID1ZqQznQ+L5dmIbPJThBe6Ec/lzVW4CGsVtmJvnRrN/\n-----END CERTIFICATE-----"

"certificateAuthorities":
  "ca1.cdachorg.cdac.in":
    "url": "https://10.109.168.201:7000"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICtzCCAl6gAwIBAgIUcJ4/JuTEgxB6uOGkFaXko6y+GAYwCgYIKoZIzj0EAwIw\ncjELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRkwFwYDVQQKDBBjZGFjaG9yZy5jZGFjLmluMR0wGwYDVQQDDBRj\nYTEuY2RhY2hvcmcuY2RhYy5pbjAeFw0yMTEwMjgyMTUyNDhaFw0zMTEwMjYyMTUy\nNDhaMHIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G\nA1UEBwwHUmFsZWlnaDEZMBcGA1UECgwQY2RhY2hvcmcuY2RhYy5pbjEdMBsGA1UE\nAwwUY2ExLmNkYWNob3JnLmNkYWMuaW4wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\nAAQp/nsf0LXRxVGxBxS5tBva7Shu4Ej7JYVjqzfqx3Ig7K7PJE239uowmWj2LQYI\nMBD5GOFEVbSTnV8jkrSfx4a9o4HRMIHOMB0GA1UdDgQWBBTdB4jf7GxiRm8+sqFJ\nk5X7gn6bGTAfBgNVHSMEGDAWgBTdB4jf7GxiRm8+sqFJk5X7gn6bGTAPBgNVHRMB\nAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI\nKwYBBQUHAwIwTAYDVR0RBEUwQ4cECm2oyYIUY2ExLmNkYWNob3JnLmNkYWMuaW6C\nFGNhMS1jZGFjaG9yZy1jZGFjLWlugglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E\nAwIDRwAwRAIgfUK5amONr79vtytTz0dR+ntk+S7TjATCU1ux+N5h1q8CIA9SBIxJ\nzG45AwZ/A0JJ852z5IzkNDzDequkvZv5+9vr\n-----END CERTIFICATE-----"
    "httpOptions":
      "verify": "false"
    "caName": "ca1"
    "registrar":
      "enrollId": "admin"
      "enrollSecret": "adminpw"
  "ca1.demoorg.cdac.in":
    "url": "https://10.109.168.201:7001"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICsjCCAligAwIBAgIULFWy6NP6oPCprgQYSatum9jKtjwwCgYIKoZIzj0EAwIw\ncDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRgwFgYDVQQKDA9kZW1vb3JnLmNkYWMuaW4xHDAaBgNVBAMME2Nh\nMS5kZW1vb3JnLmNkYWMuaW4wHhcNMjExMDI4MjE1MzIzWhcNMzExMDI2MjE1MzIz\nWjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNV\nBAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2RlbW9vcmcuY2RhYy5pbjEcMBoGA1UEAwwT\nY2ExLmRlbW9vcmcuY2RhYy5pbjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLjf\nqqex2Yk48atwCZSCO80I2VT6k3CM4sZVJQozd7UUwkKc2+jsVCinbANSu8oZHhF6\nKJt/Lmxxh67CJjVk7Jujgc8wgcwwHQYDVR0OBBYEFL/iJRL+pNiqbTj1/cg4u9V+\n1OUGMB8GA1UdIwQYMBaAFL/iJRL+pNiqbTj1/cg4u9V+1OUGMA8GA1UdEwEB/wQF\nMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEF\nBQcDAjBKBgNVHREEQzBBhwQKbajJghNjYTEuZGVtb29yZy5jZGFjLmlughNjYTEt\nZGVtb29yZy1jZGFjLWlugglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAw\nRQIhAJzO49/wQY2s/qGx/s3kjKcBlJdUDGCSAJeViA+THx3+AiBz9fAA6ckqi0qY\n6RahIW+YpROHomRWLhF9rrP8zqM6iQ==\n-----END CERTIFICATE-----"
    "httpOptions":
      "verify": "false"
    "caName": "ca1"
    "registrar":
      "enrollId": "admin"
      "enrollSecret": "adminpw"
  "ca1.actsorg.cdac.in":
    "url": "https://10.109.168.201:7002"
    "tlsCACerts":
      "pem": "-----BEGIN CERTIFICATE-----\nMIICszCCAligAwIBAgIUJSHc5UoOOiqnErRVWgZrQ6SIpRkwCgYIKoZIzj0EAwIw\ncDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRgwFgYDVQQKDA9hY3Rzb3JnLmNkYWMuaW4xHDAaBgNVBAMME2Nh\nMS5hY3Rzb3JnLmNkYWMuaW4wHhcNMjExMDI4MjE1MTEyWhcNMzExMDI2MjE1MTEy\nWjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNV\nBAcMB1JhbGVpZ2gxGDAWBgNVBAoMD2FjdHNvcmcuY2RhYy5pbjEcMBoGA1UEAwwT\nY2ExLmFjdHNvcmcuY2RhYy5pbjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIHN\nVqpIo1htIvLHAwYro6Nj6q5+lbISmfQPPWgk+yYBREdj9Z2e/QlH2EQOwbBnAp4g\nyipcdEwf/oiRV1uaKE+jgc8wgcwwHQYDVR0OBBYEFG+f/Wd2qKH1KMUeYSzt3/6A\nC7FwMB8GA1UdIwQYMBaAFG+f/Wd2qKH1KMUeYSzt3/6AC7FwMA8GA1UdEwEB/wQF\nMAMBAf8wDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEF\nBQcDAjBKBgNVHREEQzBBhwQKbajJghNjYTEuYWN0c29yZy5jZGFjLmlughNjYTEt\nYWN0c29yZy1jZGFjLWlugglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSQAw\nRgIhALOwYHdYrCYC27NEhX12tfkOzEpxjHzxwO/YSaH/E5kgAiEAtaQN5Es8dlGj\nmCBPXiWkJGs5w2eEwfgg1l0xO0tAvSM=\n-----END CERTIFICATE-----"
    "httpOptions":
      "verify": "false"
    "caName": "ca1"
    "registrar":
      "enrollId": "admin"
      "enrollSecret": "adminpw"
